### ISSUE TITLE
Floor and Ceil return double instead of int(egral)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#84] opened 2019-01-26 12:58 UTC
According to the comments `Floor()` and `Ceil()` should return an integral value.
As they accept a "double" the integral value should be of type "long".

With overloading they could even return either an integer (if a float or int is passed) or a long (if a double or long is passed).

The current implementation leads to `Compile Error: Unable to find overload for ...` if you pass eg. `5 + floor(x/5.0)` to a function requiring an "integer" (or long) as it no longer is an integer but a double.

**Comment by HurryStarfish** [comment] 2019-01-26 17:31
This is because `Double` can represent much larger numbers than `Long can`, so returning a `Long` would risk producing wrong results.
```
SuperStrict
Framework BRL.StandardIO

Local d:Double = 10000000000000000000:Double
Print d
Print Long(d)
```
Even if there was an integral type that was large enough, it still wouldn't be able to represent Infinity or NaN.
There *could* be `:Float(Float)` overloads for these functions though.

**Comment by GWRon** [comment] 2019-01-26 22:48
I never checked but assumed a int:float and long:double connection.

Nonetheless it wont return an integral value if it has decimals... Even if that is 0.00000001

**Comment by GWRon** [comment] 2019-01-28 17:43
Yes it surely does ...somehow, but it does not in BlitzMax!
if you casted it to an int you are not guaranteed to get the right number - are you?

BlitzMax represents "3.000000000..." as "2.999999999...7" or "3.00000001..." or similar. So when using a simple "int()" cast to eg. satisfy the compiler (eg. a function param needs to be "int") you might end up with either 2 or 3.
Or does that differ here? Maybe they take care of that internally already?

This is why I thought of ":int" or ":long" being the better solutions - especially as I thought (without further thinking...) that long and double are similar (except for the fraction part) and int/float are similar (except for the fractions).

**Comment by HurryStarfish** [comment] 2019-01-28 18:22
What you're thinking of is the problem of rounding errors with floating point numbers. This is completely unrelated to BlitzMax and a consequence of how computers store floating point numbers. Many fractional numbers that look simple in decimal (like `0.1`) [end up with an infinite number of digits when converted to binary](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Representable_numbers,_conversion_and_rounding). As a result, they cannot be represented accurately and need to be rounded to the nearest possible binary representation (which, in turn, doesn't look very round in decimal).
This is not a problem with integral numbers; they can be represented accurately up to a certain absolute value, and beyond that value, the rounding error will be integral. You can try this out [here](https://www.h-schmidt.net/FloatConverter/IEEE754.html).

**Comment by GWRon** [comment] 2019-01-28 18:35
I am aware of the rounding errors - which is why i gave that 2.999... example.
I am just a bit unsure how this effects ceil/floor. 

My thought was that if the return values are not "integers" ("3") but stored as doubles this might lead to trouble when cast to int. I assumed:
- I "floor" eg. "3.5:float"
- result is "3.00000...0:double"
- the result cannot get stored exactly as it is a float/double - only a "vague" representation of "3" will be
- when now casting to an "int" the "vague" representation of "3" will just get truncated - either resulting in "2" or "3"

This is what I assumed - but seemingly I was wrong (again).

**Comment by HurryStarfish** [comment] 2019-01-28 18:44
See the second paragraph of my previous post. Small integral numbers have exact representations and large ones have rounding errors that are themselves integers.

**Comment by GWRon** [comment] 2019-01-28 19:33
Maybe it is based on some misconception by me regarding the way the conversion worked. As written above I assumed some behaviour which does not seem to be the case.

Maybe my past experience with floating points and odd rounding error issues influenced my assumptions too much.

Thanks for elaborating 'bout that stuff a bit.

**Comment by woollybah** [comment] 2019-02-08 16:26
Closing, as this is working as intended. :-)

**Closed by woollybah** 2019-02-08 16:26 UTC
