### ISSUE TITLE
brl.mod/vector.mod

### ISSUE THREAD

**Issue by xlsior75** [bmx-ng/brl.mod#139] opened 2019-06-08 18:47 UTC
Windows, latest NG bmk/bcc:

[  4%] Processing:vector.bmx
Compile Error: Cyclic declaration of 'SVec2D'.
[c:/code/BlitzmaxNG810/mod/brl.mod/vector.mod/vector.bmx;51;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/brl.mod/vector.mod/vector.bmx

**Comment by HurryStarfish** [comment] 2019-06-15 14:12
Duplicate of bmx-ng/bcc/issues/453

**Closed** 2019-07-23 05:20 UTC
